[0m17:19:16.532864 [debug] [MainThread]: Got an exception trying to initialize tracking


============================== 17:19:16.567036 | 9ec97172-9d98-4fb1-8763-b504e1fca480 ==============================
[0m17:19:16.567036 [info ] [MainThread]: Running with dbt=1.10.1
[0m17:19:16.567763 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/kevinsoenandar/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:19:26.062808 [debug] [MainThread]: Starter project path: /Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/dbt/include/starter_project
[0m17:19:26.075642 [info ] [MainThread]: 
Your new dbt project "dbt_sao" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:19:26.076407 [info ] [MainThread]: Setting up your profile.
[0m17:19:36.781494 [error] [MainThread]: Encountered an error:

[0m17:19:36.796288 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/dbt/cli/requires.py", line 161, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/dbt/cli/requires.py", line 111, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/Users/kevinsoenandar/.pyenv/versions/3.12.10/envs/Setup/lib/python3.12/site-packages/click/termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m17:19:36.828980 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 20.331102, "process_in_blocks": "0", "process_kernel_time": 0.272756, "process_mem_max_rss": "99549184", "process_out_blocks": "0", "process_user_time": 1.135527}
[0m17:19:36.868839 [debug] [MainThread]: Command `dbt init` failed at 17:19:36.867003 after 20.37 seconds
[0m17:19:36.875667 [debug] [MainThread]: Flushing usage events
